### ISSUE TITLE
Failed to get chunk after a few seconds on raspberry pi

### ISSUE THREAD

**Issue by armageddon421** [badaix/snapcast#407]
Hey all,

I changed the WiFi dongle to one that supports 5GHz (DWA-171) because I had problems on this specific raspberry pi (works fine on others) but the problem got worse. This is how the log looks like:
https://gist.github.com/armageddon421/b1b29902df8f602513f42f2cbfe6f194

The symptom is that I initially hear a few seconds of music until I get the "failed to get chunk" error. After a while, it plays again for a few seconds and throws that error again and so on and so forth. This all happens while I am connected via SSH, I can actually see the log messages in realtime, so there is no complete drop of the WiFi connection. iperf runs for minutes without problems and reports >80MBit/s.

Does anyone have any Ideas?
Thank you!

**Comment by AlleyCat2017** [comment]
Hey all,
I am having the same error message using rev 0.15 on Raspberry Pi latest release. 
8-08-06 18-39-44 [Info] ServerSettings - buffer: 1000, latency: 0, volume: 100, muted: 0
metadata:{"STREAM":"music"}
2018-08-06 18-39-44 [Info] Codec: pcm
2018-08-06 18-39-44 [Notice] sampleformat: 48000:16:2
2018-08-06 18-39-44 [Info] frames: 1440
2018-08-06 18-39-44 [Info] Failed to get chunk
2018-08-06 18-39-44 [Info] diff to server [ms]: -0.001
2018-08-06 18-39-49 [Notice] No chunk received for 5000ms. Closing ALSA.

I have no idea where to look or how to proceed. 

Any ideas? 
Thank you

**Comment by AlleyCat2017** [comment]
Update:

I just found that the following command line is working. 
mplayer http://wms-15.streamsrus.com:11630 -novideo -channels 2 -srate 48000 -af format=s16le -ao pcm:file=/tmp/snapfifo 

Thanks,

**Comment by armageddon421** [comment]
Seems like you had a different problem then. I am using mopidy as an audio source. All other clients work fine, just this one has intermittent problems. I did not solve it yet.

**Comment by AlleyCat2017** [comment]
I am having no luck on setting up snapclient and snapserver using mpd, volumio or libreelec. I am getting the same error message:

8-08-06 18-39-44 [Info] ServerSettings - buffer: 1000, latency: 0, volume: 100, muted: 0
metadata:{"STREAM":"music"}
2018-08-06 18-39-44 [Info] Codec: pcm
2018-08-06 18-39-44 [Notice] sampleformat: 48000:16:2
2018-08-06 18-39-44 [Info] frames: 1440
2018-08-06 18-39-44 [Info] Failed to get chunk
2018-08-06 18-39-44 [Info] diff to server [ms]: -0.001
2018-08-06 18-39-49 [Notice] No chunk received for 5000ms. Closing ALSA.

The only way I got to connect the client with the server is using the mplayer command and explicitly sink the audio file into -ao pcm:file=/tmp/snapfifo 

I spent hours trying different configurations. I don't have any idea how to progress. I tried using older versions of the snapcast build (0.14 and 0.13) and I am getting the same error. 

Any help will be greatly appreciated. 

Thank you

**Comment by armageddon421** [comment]
@AlleyCat2017 this clearly seems to be a different issue. Maybe it would be best to open a new issue, describe what you are trying to accomplish, post all your configs and how you are starting things and list what you've already tried there.

**Comment by christf** [comment]
@armageddon421  I seem to have the same (a similar) issue. This is my log with tcpdump and snapclient logs in one terminal:

2018-10-20 13-41-08 [out] Failed to get chunk
2018-10-20 13-41-08 [out] Sleep 8, age: -6007, bufferDuration: 125
2018-10-20 13-41-08 [out] Failed to get chunk
2018-10-20 13-41-08 [out] Sleep 8, age: -6123, bufferDuration: 125
2018-10-20 13-41-08 [out] Failed to get chunk
2018-10-20 13-41-08 [out] Sleep 8, age: -6239, bufferDuration: 125
2018-10-20 13-41-08 [out] Failed to get chunk
2018-10-20 13-41-08 [out] Sleep 8, age: -6358, bufferDuration: 125
2018-10-20 13-41-08 [out] Failed to get chunk
2018-10-20 13-41-08 [out] No chunk received for 5000ms. Closing ALSA.
13:41:10.729708 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20162026:20163474, ack 6291, win 235, options [nop,nop,TS val 2898577147 ecr 3972598233], length 1448
13:41:10.730058 IP 192.168.13.136.34226 > 192.168.13.174.1704: Flags [.], ack 20163474, win 4250, options [nop,nop,TS val 3972600550 ecr 2898577147], length 0
13:41:10.729748 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20163474:20164922, ack 6291, win 235, options [nop,nop,TS val 2898577147 ecr 3972598233], length 1448
13:41:10.730493 IP 192.168.13.136.34226 > 192.168.13.174.1704: Flags [.], ack 20164922, win 4236, options [nop,nop,TS val 3972600550 ecr 2898577147], length 0
13:41:10.729782 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20164922:20166370, ack 6291, win 235, options [nop,nop,TS val 2898577147 ecr 3972598233], length 1448
13:41:10.730815 IP 192.168.13.136.34226 > 192.168.13.174.1704: Flags [.], ack 20166370, win 4222, options [nop,nop,TS val 3972600550 ecr 2898577147], length 0
13:41:10.729824 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20166370:20167818, ack 6291, win 235, options [nop,nop,TS val 2898577147 ecr 3972598233], length 1448
13:41:10.743647 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20182298:20183746, ack 6291, win 235, options [nop,nop,TS val 2898577148 ecr 3972600550], length 1448
13:41:10.743909 IP 192.168.13.136.34226 > 192.168.13.174.1704: Flags [.], ack 20183746, win 4250, options [nop,nop,TS val 3972600563 ecr 2898577148], length 0
13:41:10.783214 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20202570:20204018, ack 6291, win 235, options [nop,nop,TS val 2898577149 ecr 3972600554], length 1448
13:41:10.783247 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20204018:20205466, ack 6291, win 235, options [nop,nop,TS val 2898577149 ecr 3972600554], length 1448
13:41:10.783279 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20205466:20206914, ack 6291, win 235, options [nop,nop,TS val 2898577149 ecr 3972600554], length 1448
13:41:10.783715 IP 192.168.13.136.34226 > 192.168.13.174.1704: Flags [.], ack 20206914, win 4266, options [nop,nop,TS val 3972600603 ecr 2898577149], length 0
13:41:10.784132 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20206914:20208362, ack 6291, win 235, options [nop,nop,TS val 2898577149 ecr 3972600554], length 1448
13:41:10.784167 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20208362:20209810, ack 6291, win 235, options [nop,nop,TS val 2898577149 ecr 3972600554], length 1448
13:41:10.784195 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20209810:20211258, ack 6291, win 235, options [nop,nop,TS val 2898577149 ecr 3972600554], length 1448
13:41:10.792704 IP 192.168.13.136.34226 > 192.168.13.174.1704: Flags [.], ack 20232978, win 4266, options [nop,nop,TS val 3972600612 ecr 2898577156], length 0
13:41:10.882570 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20232978:20234426, ack 6291, win 235, options [nop,nop,TS val 2898577156 ecr 3972600565], length 1448
13:41:10.882597 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20234426:20235874, ack 6291, win 235, options [nop,nop,TS val 2898577156 ecr 3972600565], length 1448
13:41:10.882599 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20235874:20237322, ack 6291, win 235, options [nop,nop,TS val 2898577156 ecr 3972600565], length 1448
13:41:10.882602 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20237322:20238770, ack 6291, win 235, options [nop,nop,TS val 2898577156 ecr 3972600565], length 1448
13:41:10.882604 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20238770:20240218, ack 6291, win 235, options [nop,nop,TS val 2898577156 ecr 3972600565], length 1448
13:41:10.882606 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20240218:20241666, ack 6291, win 235, options [nop,nop,TS val 2898577156 ecr 3972600565], length 1448
13:41:10.882608 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20241666:20243114, ack 6291, win 235, options [nop,nop,TS val 2898577156 ecr 3972600565], length 1448
13:41:11.166142 IP 192.168.13.136.34226 > 192.168.13.174.1704: Flags [P.], seq 6291:6325, ack 20260921, win 4266, options [nop,nop,TS val 3972600986 ecr 2898577187], length 34
2018-10-20 13-41-11 [out] frames: 6000
2018-10-20 13-41-11 [out] Sleep 8, age: -4144, bufferDuration: 125
2018-10-20 13-41-11 [out] Chunk: -41441 -41441  -41441  -41441  1       0
2018-10-20 13-41-11 [out] Failed to get chunk
2018-10-20 13-41-11 [out] Sleep 8, age: -4255, bufferDuration: 125
13:41:11.197970 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [P.], seq 20260921:20260955, ack 6325, win 235, options [nop,nop,TS val 2898577263 ecr 3972600986], length 34
13:41:11.198212 IP 192.168.13.136.34226 > 192.168.13.174.1704: Flags [.], ack 20260955, win 4266, options [nop,nop,TS val 3972601018 ecr 2898577263], length 0
2018-10-20 13-41-11 [out] Failed to get chunk
2018-10-20 13-41-11 [out] Sleep 8, age: -4368, bufferDuration: 125
2018-10-20 13-41-11 [out] Failed to get chunk
2018-10-20 13-41-11 [out] Sleep 8, age: -4487, bufferDuration: 125
2018-10-20 13-41-11 [out] Failed to get chunk
2018-10-20 13-41-11 [out] Sleep 8, age: -4606, bufferDuration: 125
2018-10-20 13-41-11 [out] Failed to get chunk
2018-10-20 13-41-11 [out] Sleep 8, age: -4725, bufferDuration: 125
2018-10-20 13-41-11 [out] Failed to get chunk
2018-10-20 13-41-11 [out] Sleep 7, age: -4844, bufferDuration: 125
2018-10-20 13-41-11 [out] Failed to get chunk
2018-10-20 13-41-11 [out] Sleep 7, age: -4963, bufferDuration: 125
2018-10-20 13-41-11 [out] Failed to get chunk
2018-10-20 13-41-11 [out] Sleep 7, age: -5082, bufferDuration: 125
2018-10-20 13-41-11 [out] Failed to get chunk
2018-10-20 13-41-11 [out] Sleep 7, age: -5202, bufferDuration: 125
2018-10-20 13-41-11 [out] Failed to get chunk
2018-10-20 13-41-11 [out] Sleep 7, age: -5321, bufferDuration: 125
2018-10-20 13-41-11 [out] Failed to get chunk
2018-10-20 13-41-11 [out] Sleep 7, age: -5440, bufferDuration: 125
2018-10-20 13-41-11 [out] Failed to get chunk
2018-10-20 13-41-11 [out] Sleep 7, age: -5560, bufferDuration: 125
2018-10-20 13-41-11 [out] Failed to get chunk
2018-10-20 13-41-11 [out] Sleep 7, age: -5679, bufferDuration: 125
2018-10-20 13-41-11 [out] Failed to get chunk
2018-10-20 13-41-11 [out] Sleep 7, age: -5798, bufferDuration: 125
2018-10-20 13-41-11 [out] Failed to get chunk
2018-10-20 13-41-11 [out] Sleep 7, age: -5916, bufferDuration: 125
2018-10-20 13-41-11 [out] Failed to get chunk
2018-10-20 13-41-11 [out] Sleep 6, age: -6031, bufferDuration: 125
2018-10-20 13-41-11 [out] Failed to get chunk
2018-10-20 13-41-11 [out] Sleep 6, age: -6147, bufferDuration: 125
2018-10-20 13-41-11 [out] Failed to get chunk
2018-10-20 13-41-11 [out] Sleep 6, age: -6266, bufferDuration: 125
2018-10-20 13-41-11 [out] Failed to get chunk
2018-10-20 13-41-11 [out] Sleep 6, age: -6385, bufferDuration: 125
2018-10-20 13-41-11 [out] Failed to get chunk
2018-10-20 13-41-11 [out] Sleep 6, age: -6504, bufferDuration: 125
2018-10-20 13-41-11 [out] Failed to get chunk
2018-10-20 13-41-11 [out] No chunk received for 5000ms. Closing ALSA.
13:41:13.485162 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20260955:20262403, ack 6325, win 235, options [nop,nop,TS val 2898577835 ecr 3972601018], length 1448
13:41:13.485506 IP 192.168.13.136.34226 > 192.168.13.174.1704: Flags [.], ack 20262403, win 4250, options [nop,nop,TS val 3972603305 ecr 2898577835], length 0
13:41:13.485239 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20262403:20263851, ack 6325, win 235, options [nop,nop,TS val 2898577835 ecr 3972601018], length 1448
13:41:13.485887 IP 192.168.13.136.34226 > 192.168.13.174.1704: Flags [.], ack 20263851, win 4236, options [nop,nop,TS val 3972603305 ecr 2898577835], length 0
13:41:13.485266 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20263851:20265299, ack 6325, win 235, options [nop,nop,TS val 2898577835 ecr 3972601018], length 1448
13:41:13.486203 IP 192.168.13.136.34226 > 192.168.13.174.1704: Flags [.], ack 20265299, win 4222, options [nop,nop,TS val 3972603306 ecr 2898577835], length 0
13:41:13.486599 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20265299:20266747, ack 6325, win 235, options [nop,nop,TS val 2898577835 ecr 3972601018], length 1448
13:41:13.502858 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20310187:20311635, ack 6325, win 235, options [nop,nop,TS val 2898577839 ecr 3972603312], length 1448
13:41:13.502890 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20311635:20313083, ack 6325, win 235, options [nop,nop,TS val 2898577839 ecr 3972603312], length 1448
13:41:13.502914 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20313083:20314531, ack 6325, win 235, options [nop,nop,TS val 2898577839 ecr 3972603312], length 1448
13:41:13.506813 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20321771:20323219, ack 6325, win 235, options [nop,nop,TS val 2898577839 ecr 3972603315], length 1448
13:41:13.510454 IP 192.168.13.136.34226 > 192.168.13.174.1704: Flags [.], ack 20339147, win 4266, options [nop,nop,TS val 3972603330 ecr 2898577838], length 0
13:41:13.512610 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20339147:20340595, ack 6325, win 235, options [nop,nop,TS val 2898577839 ecr 3972603315], length 1448
13:41:13.514320 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20340595:20342043, ack 6325, win 235, options [nop,nop,TS val 2898577843 ecr 3972603316], length 1448
13:41:13.514413 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20342043:20343491, ack 6325, win 235, options [nop,nop,TS val 2898577843 ecr 3972603316], length 1448
13:41:13.514445 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20343491:20344939, ack 6325, win 235, options [nop,nop,TS val 2898577843 ecr 3972603316], length 1448
13:41:13.514475 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20344939:20346387, ack 6325, win 235, options [nop,nop,TS val 2898577843 ecr 3972603316], length 1448
13:41:13.521008 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [.], seq 20363763:20365211, ack 6325, win 235, options [nop,nop,TS val 2898577843 ecr 3972603330], length 1448
13:41:13.807038 IP 192.168.13.136.34226 > 192.168.13.174.1704: Flags [P.], seq 6325:6359, ack 20366899, win 4266, options [nop,nop,TS val 3972603627 ecr 2898577843], length 34
13:41:13.812945 IP 192.168.13.174.1704 > 192.168.13.136.34226: Flags [P.], seq 20366899:20366933, ack 6359, win 235, options [nop,nop,TS val 2898577917 ecr 3972603627], length 34
13:41:13.813202 IP 192.168.13.136.34226 > 192.168.13.174.1704: Flags [.], ack 20366933, win 4266, options [nop,nop,TS val 3972603633 ecr 2898577917], length 0
2018-10-20 13-41-13 [out] frames: 6000
2018-10-20 13-41-13 [out] Sleep 6, age: -4340, bufferDuration: 125
2018-10-20 13-41-13 [out] Chunk: -43401 -43401  -43401  -43401  1       0
2018-10-20 13-41-13 [out] Failed to get chunk
2018-10-20 13-41-13 [out] Sleep 6, age: -4450, bufferDuration: 125
2018-10-20 13-41-13 [out] Failed to get chunk
2018-10-20 13-41-13 [out] Sleep 6, age: -4566, bufferDuration: 125
2018-10-20 13-41-13 [out] Failed to get chunk
2018-10-20 13-41-13 [out] Sleep 6, age: -4682, bufferDuration: 125
2018-10-20 13-41-13 [out] Failed to get chunk
2018-10-20 13-41-13 [out] Sleep 6, age: -4800, bufferDuration: 125
2018-10-20 13-41-13 [out] Failed to get chunk
2018-10-20 13-41-13 [out] Sleep 5, age: -4918, bufferDuration: 125
2018-10-20 13-41-13 [out] Failed to get chunk
2018-10-20 13-41-13 [out] Sleep 5, age: -5037, bufferDuration: 125
2018-10-20 13-41-13 [out] Failed to get chunk
2018-10-20 13-41-13 [out] Sleep 5, age: -5156, bufferDuration: 125
2018-10-20 13-41-13 [out] Failed to get chunk
2018-10-20 13-41-13 [out] Sleep 5, age: -5275, bufferDuration: 125
2018-10-20 13-41-13 [out] Failed to get chunk
2018-10-20 13-41-13 [out] Sleep 5, age: -5392, bufferDuration: 125
2018-10-20 13-41-13 [out] Failed to get chunk
2018-10-20 13-41-13 [out] Sleep 5, age: -5509, bufferDuration: 125
2018-10-20 13-41-13 [out] Failed to get chunk
2018-10-20 13-41-13 [out] Sleep 5, age: -5628, bufferDuration: 125
2018-10-20 13-41-13 [out] Failed to get chunk
2018-10-20 13-41-13 [out] Sleep 5, age: -5746, bufferDuration: 125
2018-10-20 13-41-13 [out] Failed to get chunk
2018-10-20 13-41-13 [out] Sleep 5, age: -5864, bufferDuration: 125
2018-10-20 13-41-13 [out] Failed to get chunk
2018-10-20 13-41-13 [out] Sleep 5, age: -5984, bufferDuration: 125
2018-10-20 13-41-13 [out] Failed to get chunk
2018-10-20 13-41-13 [out] Sleep 4, age: -6103, bufferDuration: 125
2018-10-20 13-41-13 [out] Failed to get chunk
2018-10-20 13-41-13 [out] Sleep 4, age: -6220, bufferDuration: 125
2018-10-20 13-41-13 [out] Failed to get chunk
2018-10-20 13-41-13 [out] Sleep 4, age: -6338, bufferDuration: 125
2018-10-20 13-41-13 [out] Failed to get chunk
2018-10-20 13-41-13 [out] Sleep 4, age: -6456, bufferDuration: 125
2018-10-20 13-41-13 [out] Failed to get chunk
2018-10-20 13-41-14 [out] No chunk received for 5000ms. Closing ALSA.

**Comment by christf** [comment]
I am certain it is not the network because when this happens,  I can use the device using ssh.

**Comment by christf** [comment]
... and this is fixed with snapserver 15.0

**Comment by armageddon421** [comment]
I was using 0.15 all along, so that's not a fix for me.

**Comment by herrwusel** [comment]
@armageddon421 I guess this happens to you when you run snapclient under the user snapclient or also when running it under pi?

**Comment by liziru** [comment]
I has the same question when i run snapclient on embedding linux os. The version of my snapserver is 0.15.Anyone can help me? I will appreciate it very much.

**Comment by sfgabe** [comment]
Did this ever get resolved? Having the same issue on snapserver 15 also.

**Comment by badaix** [comment]
I highly recommend to update, if you do so, please report back if it's solved in the current version.

**Comment by poldy79** [comment]
I had the same issue, like in the original post. snapclient worked like a charm for month. Suddenly it did not work on all pis i had configured. snapclient on my debian notebook was still working. 

The solution was to remove /var/lib/snapserver/server.json - i still have the old one lying around, but it looks a bit messy since I was playing for years (with great success!). After starting snapserver without the file existing, my pi got audio again. the server.json was created again.
